name: SonarQube Analysis

on:
  push:
    branches:
      - '**'  # Trigger on all branches (you can specify specific branches like 'main', 'develop', etc.)
  pull_request:
    branches:
      - '**'  # Trigger for pull requests for all branches

jobs:
  sonarcloud:
    name: Analyze code with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Change this to the required version

      - name: Cache SonarQube scanner dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle', '**/*.mvn') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Set up SonarQube
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}  # SonarQube token stored in GitHub Secrets

      - name: Run SonarQube analysis
        run: |
          # Set the SonarQube host URL (only needed for self-hosted SonarQube servers)
          export SONAR_HOST_URL="http://192.168.50.4:9000"  # Replace with your SonarQube server URL
          sonar-scanner

      - name: SonarQube analysis report
        run: |
          echo "SonarQube analysis completed"
